

variables:
  # Not normally needed, but may be if some script uses `apt-get install`.
  DEBIAN_FRONTEND: noninteractive
# Locale settings do not affect the build, but might affect tests.
  LC_ALL: C

  CI_REGISTRY_IMAGE: registry.gitlab.isc.org/isc-projects/images/bind9

stages:
  - setup
  - test

ci-setup:
  stage: setup
  image: "$CI_REGISTRY_IMAGE:debian-stretch-amd64"
  script:
    - echo $CI_REGISTRY_IMAGE
    - cat /etc/motd
    - sudo apt install shellcheck

shellcheck:
  image: "$CI_REGISTRY_IMAGE:debian-stretch-amd64"
  script:
    - SCRIPTS="src/bin/keactrl/keactrl.in src/bin/admin/kea-admin.in src/bin/admin/admin-utils.sh"
    - shellcheck ${SCRIPTS}
