variables:
  # Not normally needed, but may be if some script uses `apt-get install`.
  DEBIAN_FRONTEND: noninteractive
# Locale settings do not affect the build, but might affect tests.
  LC_ALL: C

ci-setup:
  script:
    - apt install shellcheck

shellcheck:
  script:
    - SCRIPTS="src/bin/keactrl/keactrl.in src/bin/admin/kea-admin.in src/bin/admin/admin-utils.sh"
    - shellcheck ${SCRIPTS}
